%YAML:1.0
video_type: 2
filter: 6
window_size: 15
bb_path: /home/hugo/Documents/Mestrado/codigoKevyn2/dataset/exemplo/01-Light_video00001/bb.txt
video_path: /home/hugo/Documents/Mestrado/codigoKevyn2/dataset/exemplo/01-Light_video00001/lista.list
init_path: /home/hugo/Documents/Mestrado/codigoKevyn2/dataset/exemplo/01-Light_video00001.ann.txt
gt_path: /home/hugo/Documents/Mestrado/codigoKevyn2/dataset/exemplo/01-Light_video00001.ann
detect: 1
track: 1
detect_failure: 1
show: 1
repeat_video: 0
print_status: 1
valid: 0
conf: 0
